version: "3"

services:
  vue-cli:
    container_name: vue-cli
    build:
      context: ./vue-cli
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - local-net

  python:
    container_name: python
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - local-net

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      # 初期データを投入するSQLが格納されているdir
    #   - ./mysql/db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./mysql/db/mysql_data:/var/lib/mysql
      # mysql8は設定ファイルがいる
      - ./mysql/db/mysql_conf/:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - local-net

networks:
  local-net:
    driver: bridge